# Лабораторная работа 5. Структурированные типы данных

# Строки

Строки представляют собой последовательности символов. Длина строки ограничена лишь объемом оперативной памяти компьютера. 

Поддерживают обращение к элементу по индексу, получение среза, конкатенацию (оператор +), повторение (оператор *), а также проверку на вхождение (операторы in и not in).

Относятся к неизменяемым типам данных. Практически все операция в качестве значения возвращают новую строку. Поэтому для рациональной работы со строками желательно использовать специальные строковые методы.

Например, доступны следующие манипуляции:

In [ ]:
s = "Hello, World!"
print(s, type(s), id(s))

Hello, World! <class 'str'> 140071946748848


In [ ]:
s[-1] = "?"
print(s, type(s), id(s))

TypeError: ignored

Для обозначения однострочечных символов (строк) можно использовать " " или ' ':

In [ ]:
s = s[:-1] + "?" + '...'
print(s, type(s), id(s))

Их комбинация задаёт ковычки в строке:

In [ ]:
s = "Кто сказал " + '"Hello, World!"' + '?'
print(s, type(s), id(s))

Для создания многострочечных строк используйте тройные ковычки:

In [ ]:
s = """Строка 1
Строка 2
Строка 3
"""
print(s, type(s), id(s))

Если строка не присваивается переменной, то она считается строкой документирования. Такая строка сохраняется в атрибуте_doc_того объекта, в котором расположена. 

Например:

In [ ]:
def test():
    """Это описание функции"""
    pass

In [ ]:
print (test.__doc__)

Строковые методы.

Для строк есть множество методов. Посмотреть их можно по команде

In [ ]:
dir(str)

Получить информацию по каждому можно следующим образом

In [ ]:
help(str.split)

In [ ]:
help(str.join)

Рассмотрим наиболее интересные из них:
    
- метод split() позволяет разбить строку по указанному разделителю (по умолчанию - пробелам), в результате получается список слов;
- метод join() выполняет обратное действие, формирует из списка строку с определённым объединителем;
- метод format() выполняет запонение строки в зарезервированные {} места.

Например:

In [ ]:
"Хорошо бы разделить эту строку на части".split()

In [ ]:
s = "Но не каждую строку, которую надо разделить, нужно делить по пробелам!!!"

In [ ]:
s.split(', ')

In [ ]:
s.split('!')

In [ ]:
s.split('!', 1)  #  ограничем максимальное чило делений

In [ ]:
s2 = s.split(', ')
print(s2)

In [ ]:
s1 = ', '
print(s1, type(s1), id(s1))

In [ ]:
s1 = s1.join(s2)
print(s1, type(s1), id(s1))

Строковый метод format() позволяет создать строку форматной вставкой в неё данных:

In [ ]:
size = "length - {}, width - {}, height - {}"
size.format(3, 6, 2.3)

In [ ]:
size = "length - {2}, width - {0}, height - {1}"
size.format(3, 6, 2.3)

In [ ]:
size = "length - {length:5.3f}, width - {width:5.3f}, height - {height:5.3f}"
size.format(width=3.3333333, height=6.7896, length=2.3)

# Списки

Список в Python - это упорядоченный набор объектов, в который могут одновременно входить объекты разных типов (числа, строки и другие структуры). Эллементы списка доступны по индексу начинающегося с 0. Список является изменяемым типом данных - любой его эллемнт можно изменить.

Список задаётся перечислением его элементов в квадратных скобках через запятую или с помощью функции list(), например

In [ ]:
List = [1, 2.0, '3', [4]]
List

[1, 2.0, '3', [4]]

In [ ]:
List[2] = 'three'
List

[1, 2.0, 'three', [4]]

Списки поддерживают следующие базовые операции:

In [ ]:
l=[0,1,2,3,4,5,6,7]
l

[0, 1, 2, 3, 4, 5, 6, 7]

- удаление эллемента

In [ ]:
del l[3]
l

[0, 1, 2, 4, 5, 6, 7]

- добавить эллемента в заданную позицию

In [ ]:
l.insert(3,0)
l

[0, 1, 2, 0, 4, 5, 6, 7]

- добавить эллемента в конец

In [ ]:
l.append(8)
l

[0, 1, 2, 0, 4, 5, 6, 7, 8]

- добавить несколько эллементов в конец

In [ ]:
print(l, type(l), id(l))
l.extend([9,10,11])
print(l, type(l), id(l))

[0, 1, 2, 0, 4, 5, 6, 7, 8] <class 'list'> 1745891244616
[0, 1, 2, 0, 4, 5, 6, 7, 8, 9, 10, 11] <class 'list'> 1745891244616


In [ ]:
l = [6, 7]
print(l, type(l), id(l))
l = l + [4]
print(l, type(l), id(l))

[6, 7] <class 'list'> 1745890726536
[6, 7, 4] <class 'list'> 1745890726024


# Генераторы списков

Можно также воспользоваться генераторами списков:

In [ ]:
x = [i for i in range(10)]
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Генераторы списков могут иметь сложную структуру — например, состоять из нескольких вложенных циклов for и (или) содержать оператор ветвления if после цикла. Для примера получим четные элементы списка и умножим их на 10:

In [ ]:
x2 = [ i*10 for i in x if i%2 == 0 ]
print(x2)

[0, 20, 40, 60, 80]


Этот код эквивалентен коду:

In [ ]:
x2 = []
for i in x:
    if i % 2 == 0: 
        x2.append(i*10) 
print(x2)

[0, 20, 40, 60, 80]


# Копирование списков

Операция копирования для листов, имеет особенности

In [ ]:
y = x # это не копирование!!!
print(id(x), id(y))

2425413357064 2425413357064


Правильное копирование:

In [ ]:
y1 = list(x)
y2 = x.copy()
y3 = x[:]

print(y1, id(y1))
print(y2, id(y2))
print(y3, id(y3))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 2425413349128
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 2425413247688
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 2425413354888


Объединение листов:

In [ ]:
x = x[:2] + x[-2:]
print(x, type(x), id(x))

[0, 1, 8, 9] <class 'list'> 2425413318088


# Кортеж

Кортеж в Python - это упорядоченный набор объектов, в который могут одновременно входить объекты разных типов (числа, строки и другие структуры).

Его эллементы доступны по индексу начинающегося с 0. Кортеж является не изменяемым типом данных - его эллемнты нельзя менять.

Кортеж задаётся перечислением его элементов в круглых скобках через запятую или с помощью функции tuple(), например

In [ ]:
Tuple = (1, 2.0, '3', [4, 5])
print(Tuple[0],Tuple[1],Tuple[2],Tuple[3])

1 2.0 3 [4, 5]


In [ ]:
Tuple[2] = 'three'
print(Tuple[0],Tuple[1],Tuple[2],Tuple[3])

TypeError: 'tuple' object does not support item assignment

In [ ]:
Tuple[3]

[4, 5]

In [ ]:
Tuple[3] = [1, 2]
Tuple[3]

TypeError: 'tuple' object does not support item assignment

In [ ]:
Tuple[3][0]

4

In [ ]:
Tuple[3][0]=-4
Tuple[3][0]

-4

# Множества

Множества в Python - это упорядоченный набор объектов, в который могут одновременно входить объекты разных типов (числа, строки и другие структуры). В отличии от списков и картежей, множество не итерируется по индуксу.

In [ ]:
Set = set([2.0000000000000001, 1, 2, 1, '3', 4, 3])
Set

{1, 2.0, 3, '3', 4}

In [ ]:
Set.add(-1)
Set

{-1, 1, 2.0, 3, '3', 4}

Почему пропала одна 1?

Вероятно, наиболее важной операцией с множеством является операция праверки принадлежности, и для неё нужно знать только уникальные эллементы множества. По этой же причине отсутствует возможность обращаться к эллементам по индексу.

In [ ]:
x = 1

if x in Set:
    print('принадлежит множеству')
else:
    print('не принадлежит множеству')

принадлежит множеству


In [ ]:
dir(set)

['__and__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__iand__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__isub__',
 '__iter__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__rand__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__ror__',
 '__rsub__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__xor__',
 'add',
 'clear',
 'copy',
 'difference',
 'difference_update',
 'discard',
 'intersection',
 'intersection_update',
 'isdisjoint',
 'issubset',
 'issuperset',
 'pop',
 'remove',
 'symmetric_difference',
 'symmetric_difference_update',
 'union',
 'update']

In [ ]:
help(set.add)

Help on method_descriptor:

add(...)
    Add an element to a set.
    
    This has no effect if the element is already present.



# Словари

Словарь в Python - структура содержит пары "ключ" - "значение" (их порядок несущественен). Это одина из наиболее полезных и гибких структур имеющихся в Python. Словари реализованы как хэш-таблицы, так что поиск даже в больших словарях очень эффективен.

Например, с помощью словоря можно эмулировать работу оператора множественного выбора аналогичного switch:

In [ ]:
def switch_dict(x):
    return {
        "a": 1,
        "b": 2,
        "c": 3
    }.get(x, -1)

In [ ]:
switch_dict('a')

1

In [ ]:
switch_dict('6')

-1

In [ ]:
ss = {1: "a","b": 2,"c": 3}

In [ ]:
ss[1]

'a'

In [ ]:
ss['b']

2

# Массивы (numpy)

Менее стандартной, но очень полезной является структура массив, объединяющая эллементы одинакового типа.

In [ ]:
import numpy as np

In [ ]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

Очень часто возникает задача создания массива определенного размера, причем чем заполнен массив абсолютно неважно. В этом случае можно воспользоваться циклами или генераторами списков (кортежей), но NumPy для таких случаев предлагает более быстрые и менее затратные функции-заполнители.

Полезными оказываются следующие функции (по умолчанию, тип создаваемого массива - float64.):

- zeros() - заполняет массив нулями, 

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

- eye() - создаёт единичную матрицу, 

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

- empty - заполняет матрицу случайными числами, которые зависят от состояния памяти. 

In [ ]:
np.empty([3, 3])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Для создания последовательностей чисел NumPy предоставляет функции arange() и linspace(), которая возвращает одномерные массивы:

- np.arange(From, To, Step) - построить массив чисел от From (включая) до To (не включая) с шагом Step:

In [ ]:
np.arange(10)   #  От 0 до указанного числа с шагом 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(10, 20)    #  От 10 до 20 с шагом 1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(10, 100, 10)    #  Диапазон с заданным шагом

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(0, 1, 0.1)    #  Аргументы могут иметь тип float

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

- np.linspace(From, To, Num) - построить массив чисел от From (включая) до To (включая) с колличеством эллементов Num:

In [ ]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [ ]:
A[0,0] = 5.1

In [ ]:
A = A/2

In [ ]:
A

array([[2.5, 1. ],
       [1.5, 2. ]])

# Упражнение 1.

С клавиатуры (неограниченное количество раз) вводится некоторая последовательность значений, необходимо сохранить только уникальные символы (цифры и буквы). И после окончания ввода вывести сохранённые символы.

In [ ]:
flag = True
i = 1
while flag:
  x = input('Введите значение ')
  if x == '0':
    flag = False
  else:
    if i == 1:
     a = set(x)
    else:
     a.add(x)
  i += 1
  print(a)

# Упражнение 2. Эффективный размер массива (стек).

Стек, дека, очередь. Массив с дополнительными параметрами (размер выделенной памяти и объём занятой памяти). Позволяют за константное время добавлять и убирать элементы в начало и конец эффективного размера массива.

Напишите функцию которая реализует работу стека: 
1. внутри определён массив numpy заданного размера и целочисленный параметр фиксирующий степень заполненности массива;
2. функция принимает значение x и индиксатор действия (0 - чтение из стека, 1 - запись в стек); в случае чтения возвращает значение из конца массива или False, если стек пуст; при записи возвращает логическую переменную индикатор успешности операции;
3. при операциях чтения и записи должна проверяться корректность этого действия связанная с размерами стека.

In [1]:
import numpy as np 
n = 100
I = 0
stack = np.zeros(n)
def Stack(x,y):
  global stack, n , I
  if y == 0:
    if I == 0:
      return False 
    else:
      return stack[I-1]
  elif I < n-1:
    stack[I] = x
    I += 1
    return True
  else:
    return False

# Упражнение 3. Эффективный размер массива (множество).

Как мы уже поняли, множество в Python это совокупность уникальных объектов не доступных по индексу. Адаптируйте предыдущую программу к работе в таком режиме.

Т.е.: 
1. дописываться могут только значения не записанные ранее;
2. функция принимает одно значение x (True - вывод всего множества, числовое значение - запись в множество); в случае если множество пусто возвращается False; при записи возвращает логическую переменную индикатор успешности операции;
3. при операциях чтения и записи должна проверяться корректность этого действия связанная с размерами множества.

P.S. Попробуйте реализовать пункт с выводом значений по возрастанию через работу с дополнительным массивом индексов (перестановок). Или начиная запись в множество с середины массива...

In [3]:
arr = np.zeros (n)

In [2]:
import numpy as np
n = 3
arr = np.zeros(n)
i = -1
def stack1(x=True):
  global arr , i
  if x == True:
    if i == -1:
      return (False)
    else:
      return (arr)
  elif i < n-1:
    if x not in arr:
      arr[i] = x
      print(arr)
      i += 1
      return (True)
    else:
      print('Такой элемент уже входит в массив arr')
  else: 
    print('Массив arr полностью заполнен')

# Функции для итерируемых объектов.

Наиболее полезными для итерируем объектов являются функции:
- map() - позволяет применить заданную функцию к каждому элементу последовательности, возвращает объект, поддерживающий итерации,
- zip() - возвращает кортеж, содержащий элементы последовательностей расположенных на одинаковом смещении,
- filter() - позволяет выполнить проверку элементов последовательности.

In [ ]:
def fun(elem):
    return elem + 10 

arr = [1, 2, 3, 4, 5]
print(list(map(fun, arr)))

[11, 12, 13, 14, 15]


In [ ]:
list(zip([ 1, 2, 3], [4, 5, 6], [7, 8, 9]))

[(1, 4, 7), (2, 5, 8), (3, 6, 9)]

In [ ]:
arrl = [1, 2, 3, 4, 5]
arr2 = [10, 20, 30, 40, 50]
arrЗ = [100, 200, 300, 400, 500]

arr = [х + у + z for (х, у, z) in zip(arrl, arr2, arrЗ)]
print(arr)

[111, 222, 333, 444, 555]


или что тоже самое

In [ ]:
def fun(a,b,c):
    return a+b+c 

print(list(map(fun, arrl, arr2, arrЗ)))

[111, 222, 333, 444, 555]


In [ ]:
def fun(elem):
    return elem % 2 == 0

list(filter(fun, arr))

[222, 444]

# Генераторы словарей

In [ ]:
keys = ["а", "Ь", "c"]
values = [1, 2, 3] 
dict_kv = {k: v for (k, v) in zip(keys, values)}
dict_kv

{'а': 1, 'Ь': 2, 'c': 3}

# Упражнение 4.

Создайте функцию принимающую двумерную таблицу, работающую со всеми возможными итерируемыми типами данных подходящими для её хранения (лист, словарь, картеж, массив и т.д.). Функция должна выполнять вывод строк этой таблици в случайном порядке. 

Насколько сложно было бы сделать аналогичный вывод для столбцов?

In [4]:
import random
import numpy
def tb(table):
    result = [0, 0]
    if type(table) is dict:
        result[0] = [x for x in table.keys()]
        result[1] = [x for x in table.values()]
    else:
        result[0] = [x for x in table[0]]
        result[1] = [x for x in table[1]]
    startLine = random.randint(0, 1)
    return result[startLine], result[not(startLine)]
    
print(tb({1:4, 2:5, 3:6}))
print(tb([[1,2,3], [4,5,6]]))
print(tb(tuple([[1,2,3], [4,5,6]])))
print(tb(numpy.array([[1,2,3], [4,5,6]])))

([4, 5, 6], [1, 2, 3])
([4, 5, 6], [1, 2, 3])
([1, 2, 3], [4, 5, 6])
([4, 5, 6], [1, 2, 3])


# Домашнее задание (базовое):

# Задание 1.

С клавиатуры вводится строка, включающая строчные и прописные буквы. Требуется вывести ту же строку в изменённом регистре, тип регистра зависит от того, каких букв больше. При равном количестве букв в заглавном и проптсном регистре - выводится оригинальная строка. 

Например, вводится строка "HeLLo World", она должна быть преобразована в "hello world", потому что в исходной строке малых букв больше. 

В программе можно использовать строковые методы: upper() (преобразование к верхнему регистру) и lower() (преобразование к нижнему регистру), isupper() и islower() (проверяющие регистр строки или символа).

In [ ]:
a=input()
b=0
c=0
for i in a:
    if i.isupper() == True:
        c += 1
    else:
        b += 1      
if b > c:
    print(a.lower())
elif b == c:
    print(a)
else:
    print(a.upper())

HeLLo World
hello world


# Задание 2

Дано слово "объектно-ориентированный". Используя индексацию и срезы составьте из него как можно больше слов "объект", "ориентир", "тир", "кот", "рента" и тд. Выведите их на экран.

In [ ]:
a=[i for i in "объектно-ориентированный"]
print(''.join(a[9:17]))
print(''.join(a[0:6]))
print(''.join([a[10],a[19],a[4],a[3],a[14],a[19]]))
print(''.join([a[4],a[9],a[10],a[9],a[18],a[19]]))
print(''.join([a[4], a[0],a[10],a[7],a[6],a[19]]))
print(''.join([a[20], a[17],a[18],a[22],a[23]]))
print(''.join([a[10],a[0],a[5],a[19]]))
print(''.join([a[5], a[10], a[9], a[6]]))
print(''.join([a[6],a[9], a[10], a[19]]))
print(''.join([a[6],a[9], a[5], a[19]]))
print(''.join([a[4],a[11], a[13], a[0]]))
print(''.join([a[1],a[0], a[10], a[14]]))
print(''.join([a[5], a[7],a[6]]))
print(''.join([a[5], a[7],a[4]]))
print(''.join([a[10],a[0],a[5],]))
print(''.join([a[10], a[7],a[4]]))
print(''.join([a[4], a[11],a[14]]))
print(''.join([a[16], a[17],a[18]]))
print(''.join(a[14:17]))
print(a[0]+a[16])
#['о', 'б', 'ъ', 'е', 'к', 'т', 'н', 'о', '-', 'о', 'р', 'и', 'е', 'н', 'т', 'и', 'р', 'о', 'в', 'а', 'н', 'н', 'ы', 'й']
#  0    1     2   3    4     5    6    7   8     9   10   11   12   13    14  15   16   17   18  19    20   21   22   23

ориентир
объект
ракета
корова
корона
новый
рота
трон
нора
нота
кино
борт
тон
ток
рот
рок
кит
ров
тир
ор


# Задание 3

Строковый метод isdigit() проверяет, состоит ли строка только из цифр. Напишите программу, которая запрашивает с ввода целые числа и выводит их сумму. В случае некорректного ввода программа не должна завершаться с ошибкой, а должна продолжать работу, удаляя из введённой строки все символы кроме цифр. При отсутствии цифр запрс пользователю повторяется.

Обработчик исключений try-except использовать нельзя.

In [ ]:
x = input()
if x.isdigit == True:
    x = int()
    n = len(x) 
    y = 0
    for i in range(n):
        y = y + x[i]
else:
    x =[i for i in x]
    y = 0
    for i in x:
        if 'a' <= i <= 'z' or 'A' <= i <= 'Z' or'а' <= i <= 'я' or 'А' <= i <= 'Я': 
            y = y + 0
        else:
            i = int(i)
            y = y + i
print(y)

126y
9


# Задание 4

Создайте словарь, где ключами являются числа, а значениями – строки. Примените к нему метод items(), полученный объект dict_items передайте в написанную вами функцию, которая создает и возвращает новый словарь, "обратный" исходному, т. е. ключами являются строки, а значениями – числа. 

In [ ]:
d={0: "aaa", 1: "bbb", 2: "ccc", 3: "abc"}
def y(x):
    keys=[]
    values=[]
    for i in list(x.items()):
        values.append(list(i)[0])
        keys.append(list(i)[1])
    return {k: v for (k, v) in zip(keys, values)}          
print(y(d))   

{'aaa': 0, 'bbb': 1, 'ccc': 2, 'abc': 3}


# Задание 5. (Снова в школу...)

Опишите структуру данных (базу данных) на основе словаря и интерфейс работы с ней (функцию). 

Создайте словарь school, и наполните его данными, которые бы отражали количество учащихся в разных классах (1а, 1б, 2б, 6а, 7в и т.п.). И функцию для внесения изменений в словарь в рамках следующего функционала: 
а) в одном из классов изменилось количество учащихся; 
б) в школе появился новый класс; 
с) в школе был расформирован (удален) класс, в связи с чем ученики были равномерно распределены по другим; 
d) выгрузка данных: общее количество учащихся в школе, общее колличество классав, распределение учеников по классам.

P.S. Дополнительно.

Подумайте как лучше всего хранить такую базу данных в файле. Попробуйте реализовать свою идею.

# Домашнее задание (дополнительное):

# Задание. Реверс словаря.

Создайте словарь, где ключами являются цифры, а значениями – строки. Передайте словарь в функцию, которая создает и возвращает новый словарь, "обратный" исходному, при этом ключами являются буквы составляющие строки, а значениями – числа составленные из цифр в порядке соответствующем.

Например: 

Исходный словарь: {1: 'аcc', 2: 'сab', 3: 'ccb'}

Выходной словарь: {'а': 12, 'b': 23, 'c': 11233}

# Задание. Разрезание таблиц. 

Заполните квадратную таблицу порядка n по спирали по часовой стрелке начиная с левого верхнего угла. В напишите функцию принимающую данную таблицу в подходящем формате, найдите строку с наибольшим количеством нулей и столбец с максимальной суммой элементов. Разрежьте по этой строке и столбцу таблицу и верните из функции получившийся результат как отдельные таблицы, после чего выведете их на печать.

# Задание. Пары.

На вход программы поступает последовательность из N целых положительных чисел, все числа в последовательности различны. Рассматриваются все пары различных элементов последовательности (элементы пары не обязаны стоять в последовательности рядом, порядок элементов в паре не важен). Необходимо определить количество пар, для которых произведение элементов делится на 26.
Описание входных и выходных данных.

В первой строке входных данных задаётся количество чисел N (1 ≤ N ≤ 1000). В каждой из последующих N строк записано одно целое положительное число, не превышающее 10 000.

В качестве результата программа должна напечатать одно число: количество пар, в которых произведение элементов кратно 26.

Пример входных данных: 4 2 6 13 39

Пример выходных данных: 4

Из четырёх заданных чисел можно составить 6 попарных произведений:

2·6 = 12 

2·13 = 26 

2·39 = 78 

6·13 = 78

6·39 = 234 

13·39 = 507

Из них на 26 делятся 4 произведения:

2·13=26

2·39=78

6·13=78

6·39=234

Требуется написать эффективную по времени и по памяти программу для решения описанной задачи.

(Программа считается эффективной по времени, если при увеличении количества исходных чисел N в k раз время работы программы увеличивается не более чем в k раз. Программа считается эффективной по памяти, если память, необходимая для хранения всех переменных программы, не превышает 1 Кбайт и не меняется с ростом N.)